# Project-level Gradle settings
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC -XX:+ParallelRefProcEnabled
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX properties
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# KSP Optimizations
ksp.incremental=true
ksp.incremental.intermodule=true

# Kotlin properties
kotlin.code.style=official
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
