import typer
from cli.admin_cli import reset_admin_command
from cli.clean import clean_command
from cli.config import config_command
from cli.dev import dev_command
from cli.doctor import doctor_command
from cli.formatting import lint_command
from cli.importer import import_osm_command, seed_command
from cli.logs import logs_command
from cli.migrate import downgrade_command, makemigrations_command, migrate_command
from cli.prod import prod_command
from cli.shell import shell_command
from cli.testing import test_command
from cli.version import version_command

app = typer.Typer(
    name="start.py",
    help="🚀 Local Tourism Guide Backend Professional Developer CLI",
    add_completion=False,
    rich_markup_mode="rich"
)

# Register CLI Commands
app.command("dev", help="🚀 Start local development servers (FastAPI API + Celery Worker)")(dev_command)
app.command("prod", help="⚡ Run production HTTP server (Gunicorn / Uvicorn workers)")(prod_command)
app.command("doctor", help="🩺 Run infrastructure health & dependency diagnostics")(doctor_command)
app.command("migrate", help="🗄️ Run Alembic database migration upgrade to head")(migrate_command)
app.command("makemigrations", help="📝 Generate autogenerated Alembic migration script")(makemigrations_command)
app.command("downgrade", help="↩️ Downgrade Alembic database migration revision")(downgrade_command)
app.command("seed", help="🌱 Seed default tourist categories into database")(seed_command)
app.command("reset-admin", help="🔑 Reset admin password or create admin account")(reset_admin_command)
app.command("import-osm", help="🌍 Import tourist places from OpenStreetMap Overpass API")(import_osm_command)
app.command("test", help="🧪 Run Pytest automated test suite")(test_command)
app.command("lint", help="🧹 Run static code analysis and formatting checks")(lint_command)
app.command("clean", help="🗑️ Remove Python cache files and build artifacts")(clean_command)
app.command("logs", help="📋 Tail application log file (logs/app.log)")(logs_command)
app.command("shell", help="🐍 Open interactive Python REPL with backend models pre-loaded")(shell_command)
app.command("config", help="🔍 Inspect environment configuration with masked secrets")(config_command)
app.command("version", help="ℹ️ Display backend component software versions")(version_command)


@app.callback(invoke_without_command=True)
def main(ctx: typer.Context):
    """🚀 Local Tourism Guide Backend Professional Developer CLI"""
    if ctx.invoked_subcommand is None:
        from cli.utils import render_banner
        render_banner()
        typer.echo(ctx.get_help())


if __name__ == "__main__":
    app()
