import subprocess
import typer
from rich.console import Console

console = Console()


def migrate_command():
    """Run Alembic database migrations to upgrade to head."""
    console.print("[bold green]Running Alembic migration upgrade head...[/bold green]")
    try:
        subprocess.run(["alembic", "upgrade", "head"], check=True)
        console.print("[bold green]Database migrations applied successfully.[/bold green]")
    except Exception as e:
        console.print(f"[bold red]Migration upgrade failed: {str(e)}[/bold red]")


def makemigrations_command(message: str = typer.Option("auto migration", "-m", "--message", help="Migration message")):
    """Generate autogenerated Alembic migration revision script."""
    console.print(f"[bold cyan]Generating migration with message: '{message}'...[/bold cyan]")
    try:
        subprocess.run(["alembic", "revision", "--autogenerate", "-m", message], check=True)
        console.print("[bold green]Migration script generated successfully.[/bold green]")
    except Exception as e:
        console.print(f"[bold red]Migration generation failed: {str(e)}[/bold red]")


def downgrade_command(revision: str = typer.Option("-1", "-r", "--revision", help="Target revision")):
    """Downgrade Alembic database migration."""
    console.print(f"[bold yellow]Downgrading database migration to: '{revision}'...[/bold yellow]")
    try:
        subprocess.run(["alembic", "downgrade", revision], check=True)
        console.print("[bold green]Database migration downgraded successfully.[/bold green]")
    except Exception as e:
        console.print(f"[bold red]Migration downgrade failed: {str(e)}[/bold red]")
