package com.example.nearby.presentation.itinerary.adapter

import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.recyclerview.widget.DiffUtil
import androidx.recyclerview.widget.ListAdapter
import androidx.recyclerview.widget.RecyclerView
import com.example.nearby.R
import com.tourismguide.app.data.remote.dto.ItineraryResponseDto

data class ChatMessage(
    val id: String = java.util.UUID.randomUUID().toString(),
    val text: String,
    val isUser: Boolean,
    val itineraryData: ItineraryResponseDto? = null,
    val agentName: String? = null,
    val isAgentStep: Boolean = false,
    val timestamp: String = java.text.SimpleDateFormat("hh:mm a", java.util.Locale.US).format(java.util.Date())
)

class ChatAdapter(
    private val onViewItineraryClick: (ItineraryResponseDto) -> Unit
) : ListAdapter<ChatMessage, RecyclerView.ViewHolder>(ChatDiffCallback()) {

    companion object {
        private const val TYPE_USER = 1
        private const val TYPE_AI = 2
        private const val TYPE_AGENT_STEP = 3
    }

    override fun getItemViewType(position: Int): Int {
        val msg = getItem(position)
        return when {
            msg.isAgentStep -> TYPE_AGENT_STEP
            msg.isUser -> TYPE_USER
            else -> TYPE_AI
        }
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
        val inflater = LayoutInflater.from(parent.context)
        return when (viewType) {
            TYPE_USER -> {
                val view = inflater.inflate(R.layout.item_chat_user, parent, false)
                UserMessageViewHolder(view)
            }
            TYPE_AGENT_STEP -> {
                val view = inflater.inflate(R.layout.item_chat_agent_step, parent, false)
                AgentStepViewHolder(view)
            }
            else -> {
                val view = inflater.inflate(R.layout.item_chat_ai, parent, false)
                AiMessageViewHolder(view)
            }
        }
    }

    override fun onBindViewHolder(holder: RecyclerView.ViewHolder, position: Int) {
        val message = getItem(position)
        when (holder) {
            is UserMessageViewHolder -> holder.bind(message)
            is AiMessageViewHolder -> holder.bind(message)
            is AgentStepViewHolder -> holder.bind(message)
        }
    }

    inner class UserMessageViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
        private val tvText: TextView = itemView.findViewById(R.id.tv_chat_user_text)
        private val tvTime: TextView? = itemView.findViewById(R.id.tv_chat_user_time)

        fun bind(message: ChatMessage) {
            tvText.text = message.text
            tvTime?.text = message.timestamp
        }
    }

    inner class AiMessageViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
        private val tvText: TextView = itemView.findViewById(R.id.tv_chat_ai_text)
        private val btnViewItinerary: TextView = itemView.findViewById(R.id.btn_chat_view_itinerary)
        private val tvAttribution: TextView? = itemView.findViewById(R.id.tv_agent_attribution)

        fun bind(message: ChatMessage) {
            tvText.text = message.text

            if (message.itineraryData != null) {
                btnViewItinerary.visibility = View.VISIBLE
                val title = if (message.itineraryData.destination.isNotEmpty()) message.itineraryData.destination else "Itinerary"
                btnViewItinerary.text = "View '$title' Itinerary ➔"
                btnViewItinerary.setOnClickListener { onViewItineraryClick(message.itineraryData) }
            } else {
                btnViewItinerary.visibility = View.GONE
            }

            if (!message.agentName.isNullOrEmpty()) {
                tvAttribution?.visibility = View.VISIBLE
                tvAttribution?.text = "Generated by ${message.agentName}"
            } else {
                tvAttribution?.visibility = View.GONE
            }
        }
    }

    inner class AgentStepViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
        private val tvAgentName: TextView = itemView.findViewById(R.id.tvAgentStepName)
        private val tvMessage: TextView = itemView.findViewById(R.id.tvAgentStepMessage)

        fun bind(message: ChatMessage) {
            tvAgentName.text = "🧠 ${message.agentName ?: "AI Agent"}"
            tvMessage.text = message.text
        }
    }

    class ChatDiffCallback : DiffUtil.ItemCallback<ChatMessage>() {
        override fun areItemsTheSame(oldItem: ChatMessage, newItem: ChatMessage): Boolean {
            return oldItem.id == newItem.id
        }

        override fun areContentsTheSame(oldItem: ChatMessage, newItem: ChatMessage): Boolean {
            return oldItem == newItem
        }
    }
}
